### PR TITLE
Update .gitignore

### PR DESCRIPTION
**Pull request by MrMusic**

### CODE REVIEW

**Comment by Erftralle** [comment]
I don't understand this pull request 😲 .

If you don't want .gitignore and .gitattributes to be tracked why than not just remove it from the repository? 

See also [here](https://stackoverflow.com/questions/10176875/add-gitignore-to-gitignore/10177000) .

**Comment by MrMusic** [comment]
>If you don't want .gitignore and .gitattributes to be tracked why than not just remove it from the repository?

I want to make sure that these git files are no longer included in the zip.
Now i try to delete it. Thanks for the hint.

**Comment by Erftralle** [comment]
> I want to make sure that these git files are no longer included in the zip.

Do you mean this [Zip](https://github.com/JoomGalleryfriends/JoomreCaptcha/archive/master.zip) provided by GitHub? It doesn't really matter if the files are included because they won't be installed unless they appear in the extension's XML file (either explicitly or as part of a directory).

There is the possibility to attach a binary to each release which contains all files you want, of course this would be an additional working step when creating a new release.

**Comment by MrMusic** [comment]
>Do you mean this Zip provided by GitHub? It doesn't really matter if the files are included because they won't be installed unless they appear in the extension's XML file (either explicitly or as part of a directory).

If the files are unnecessary they shouldn't be included in the zip either.
Even if they are not installed in joomla.


>There is the possibility to attach a binary to each release which contains all files you want, of course this would be an additional working step when creating a new release.

I am here for the easier way to remove the files from the repo.

Thanks for the merge.

**Pull request merged**
